In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("marketing campaign details.csv")
df.head(5)

           CampaignName         Type  AverageSpend  AverageROI  TotalCampaigns
0      Social Media Ads      Digital      26602.11        0.66             133
1       Email Marketing      Digital      25617.97        0.60             117
2        TV Commercials  Traditional      26301.87        0.45             113
3     Search Engine Ads      Digital      26407.21        0.60             146
4  Influencer Marketing      Digital      24887.26        1.10             125

In [3]:
df.isnull()

   CampaignName   Type  AverageSpend  AverageROI  TotalCampaigns
0         False  False         False       False           False
1         False  False         False       False           False
2         False  False         False       False           False
3         False  False         False       False           False
4         False  False         False       False           False
5         False  False         False       False           False
6         False  False         False       False           False
7         False  False         False       False           False

In [4]:
df.isnull().sum()

CampaignName      0
Type              0
AverageSpend      0
AverageROI        0
TotalCampaigns    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.describe()

       AverageSpend  AverageROI  TotalCampaigns
count      8.000000    8.000000        8.000000
mean   25672.137500    0.675000      125.000000
std      740.462955    0.187997       11.795883
min    24633.310000    0.450000      113.000000
25%    25053.767500    0.600000      116.000000
50%    25718.035000    0.635000      122.000000
75%    26328.205000    0.690000      133.250000
max    26602.110000    1.100000      146.000000

In [7]:
df.dtypes

CampaignName       object
Type               object
AverageSpend      float64
AverageROI        float64
TotalCampaigns      int64
dtype: object

In [8]:
df_campaign_perf = pd.read_csv("marketing campaign performance.csv")
df_campaign_perf.head(5)

,CampaignID,CampaignName,Region,Industry,Spend,Impressions,Clicks,Conversions,Revenue,ROI
0,1,Radio Ads,Oceania,Education,41696.19,466285,3616,1678,38360.4948,-0.080000
1,2,Search Engine Ads,North America,Tech,4366.93,984250,19824,1234,6070.0327,0.390000
2,3,Influencer Marketing,North America,Education,21790.55,424758,6510,1830,49464.5485,1.932580
3,4,Radio Ads,North America,Finance,5048.27,434528,153,335,6057.9240,0.200000
4,5,TV Commercials,Africa,Retail,26218.22,448458,19059,1544,51912.0756,0.672641

In [10]:
df_campaign_perf.dtypes

CampaignID        int64
CampaignName     object
Region           object
Industry         object
Spend           float64
Impressions       int64
Clicks            int64
Conversions       int64
Revenue         float64
ROI             float64
dtype: object

In [12]:
df_campaign_perf.isnull().sum()

CampaignID      0
CampaignName    0
Region          0
Industry        0
Spend           0
Impressions     0
Clicks          0
Conversions     0
Revenue         0
ROI             0
dtype: int64

In [13]:
df_campaign_perf.duplicated().sum()

np.int64(0)

In [14]:
df_campaign_perf.describe()

,CampaignID,Spend,Impressions,Clicks,Conversions,Revenue,ROI
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,25694.414240,503257.97100,10255.241000,1044.279000,42540.575525,0.676252
std,288.819436,14314.985157,282213.47336,5807.802902,583.086478,28029.905329,0.554042
min,1.000000,1009.230000,12187.00000,116.000000,10.000000,948.657400,-0.358571
25%,250.750000,12834.105000,274193.75000,5037.500000,528.500000,19076.807700,0.230000
50%,500.500000,26644.125000,493448.50000,10724.000000,1100.500000,38457.938700,0.640000
75%,750.250000,37916.417500,748799.00000,15122.250000,1552.000000,61926.744700,1.080000
max,1000.000000,49985.980000,999336.00000,19989.000000,1996.000000,120105.933000,2.957234

In [16]:
df_campaign_perf.shape

(1000, 10)

In [17]:
df_region_perf = pd.read_csv("region performance.csv")

In [18]:
df_region_perf.head(5)

          Region  TotalSpend  TotalRevenue  AverageROI
0         Africa  5057866.40    8606148.78        0.73
1           Asia  4544602.41    7392217.32        0.66
2         Europe  4290993.91    7025102.32        0.64
3  North America  4469221.50    7511004.90        0.75
4        Oceania  4121513.28    6619546.50        0.62

In [19]:
df_region_perf.describe()

         TotalSpend  TotalRevenue  AverageROI
count  6.000000e+00  6.000000e+00    6.000000
mean   4.282402e+06  7.090096e+06    0.676667
std    6.132758e+05  1.067197e+06    0.051640
min    3.210217e+06  5.386556e+06    0.620000
25%    4.163883e+06  6.720935e+06    0.645000
50%    4.380108e+06  7.208660e+06    0.660000
75%    4.525757e+06  7.481308e+06    0.712500
max    5.057866e+06  8.606149e+06    0.750000

In [20]:
df_region_perf.shape

(6, 4)

In [21]:
df_region_perf.isnull().sum()

Region          0
TotalSpend      0
TotalRevenue    0
AverageROI      0
dtype: int64

In [22]:
df_region_perf.duplicated().sum()

np.int64(0)

In [23]:
df_campaign_perf["ROI_Category"] = np.where(df_campaign_perf['ROI'] > 0.5, "High ROI", np.where(df_campaign_perf['ROI'] > 0.2, "Medium ROI", "Low ROI"))

In [24]:
print(df_campaign_perf["ROI_Category"])

0         Low ROI
1      Medium ROI
2        High ROI
3         Low ROI
4        High ROI
          ...
995      High ROI
996       Low ROI
997      High ROI
998       Low ROI
999      High ROI
Name: ROI_Category, Length: 1000, dtype: object

In [25]:
df_campaign_perf['Performance'] = np.where(
    df_campaign_perf['Revenue'] > df_campaign_perf['Revenue'].median(),
    'Above Average',
    'Below Average'
)

In [26]:
print(df_campaign_perf['Performance'])

0      Below Average
1      Below Average
2      Above Average
3      Below Average
4      Above Average
           ...
995    Above Average
996    Below Average
997    Above Average
998    Below Average
999    Above Average
Name: Performance, Length: 1000, dtype: object

In [27]:
avg_roi = np.mean(df_campaign_perf['ROI'])
median_roi = np.median(df_campaign_perf['ROI'])
std_roi = np.std(df_campaign_perf['ROI'])
percentile_90 = np.percentile(df_campaign_perf['ROI'], 90)

In [28]:
print("Average ROI is: ", avg_roi)
print("Median ROI is: ", median_roi)
print("Standard Deviation ROI is: ", std_roi)
print("90th Percentile ROI is: ", percentile_90)

Average ROI is:  0.6762524680608561
Median ROI is:  0.64
Standard Deviation ROI is:  0.5537651421376055
90th Percentile ROI is:  1.3709558694984918